apiVersion: v1
kind: Service
metadata:
  name: cart-service
spec:
  selector:
    app: cart
  type: NodePort
  ports:
    - protocol: TCP
      port: 8001 #TODO
      targetPort: 8001 # TODO
      nodePort: 30216
---
apiVersion: v1
kind: Service
metadata:  
  name: cart-grpc-service
spec:
  selector:    
    app: cart-grpc
  type: NodePort
  ports:  
    - protocol: TCP
      port: 8002 # TODO
      targetPort: 8002 # TODO
      nodePort: 30217