basePath: /products
host: localhost:8000
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: Micorservice for handling admin auth.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Auth Admin Microservice
  version: "1.0"
paths:
  /:
    get:
      consumes:
      - application/json
      description: API to check Admin Auth health
      produces:
      - plain/text
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Health Check Route
      tags:
      - Health
swagger: "2.0"
