pipeline {
    
    agent any

    tools {
        go '1.17'
    }

    environment {
		DOCKERHUB_CREDENTIALS=credentials('docker-hub')
        PATH = "$PATH:/usr/local/bin"
	}
    
    stages {

        stage ("clone") {
            steps {
                git branch: 'customer-account', url: "https://github.com/swiggy-2022-bootcamp/cdp-team2.git"
            }
        }

        stage("build") {

            steps {
                echo 'building the application...'
                sh 'ls'
                sh script:'''
                    #!/bin/bash
                    cd ./CustomerAccount
                    pwd
                    go mod tidy
                    cd ./cmd/server
                    go build .
                '''
            }
        }

        stage("test") {

            steps {
                echo 'testing the application...'
                sh script:'''
                    pwd
                    cd ./CustomerAccount
                    go test -v ./...
                '''
            }
        }

        stage("image build") {

			steps {
                echo 'building the docker image...'
				sh script:'''
                    pwd
                    cd ./CustomerAccount
                    docker build -t swiggyteam2/customer-account:latest .
                '''
			}
		}

        stage("docker login") {

			steps {
                echo 'loging into docker...'
                sh 'docker --version'
				sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
			}
		}

        stage("push image to dockerhub") {

            steps {
                sh 'docker --version'
                echo 'pushing the image to docker hub...'
                sh 'docker push swiggyteam2/customer-account:latest'
            }
        }
    }

    post {
		always {
		    sh 'docker logout'
		}
	}
}
