version: '3.8'
services:
  account-frontstore:
    build: .
    container_name: account-frontstore
    restart: always
    ports:
      - "8050:8050"
    extra_hosts:
      - "localhost:host-gateway"
    volumes:
      - ./app
