basePath: /
host: localhost:8080
info:
  contact:
    name: API Support
    url: http://demo.com/support
  description: This is customers CRUD service.
  termsOfService: demo.com
  title: Customers API
  version: "1.0"
paths:
  /health:
    get:
      consumes:
      - application/json
      description: API to check Customers-admin's health
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Health Check Route
      tags:
      - Health
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
  BasicAuth:
    type: basic
swagger: "2.0"
