definitions:
  models.HealthCheck:
    properties:
      status:
        example: UP
        type: string
    type: object
  models.Reward:
    properties:
      customerId:
        example: "1243"
        type: string
      description:
        example: Reward points in celebration of 50 years of Company ABC
        type: string
      points:
        example: 200
        type: integer
    type: object
info:
  contact: {}
paths:
  /reward/v1/healthcheck:
    get:
      description: Returns json stating with pass status and http response code 200
        OK, otherwise returns http response code 500 Internal Server Error.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.HealthCheck'
        "500":
          description: ""
      summary: Checks the health of the microservice
      tags:
      - healthcheck
  /reward/v1/reward/{id}:
    post:
      consumes:
      - application/json
      description: This API allows Admin to directly add reward points to the customer.
        It accepts reward points and description in the request body, and on successful
        insertion in database, it returns 200 OK.
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Reward'
        "500":
          description: ""
      summary: Add reward points to the customer
      tags:
      - healthcheck
swagger: "2.0"
