info:
  contact: {}
paths:
  /reward/v1/healthcheck:
    get:
      description: Returns json stating with pass status and http response code 200
        OK, otherwise returns http response code 500 Internal Server Error.
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "500":
          description: ""
      summary: Checks the health of the microservice
      tags:
      - healthcheck
swagger: "2.0"
