// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/swiggy-2022-bootcamp/cdp-team2/Shipping/services (interfaces: IService)

// Package mock_services is a generated GoMock package.
package mock_services

import (
	gomock "github.com/golang/mock/gomock"
	models "github.com/swiggy-2022-bootcamp/cdp-team2/Shipping/dao/models"
	shipping "github.com/swiggy-2022-bootcamp/cdp-team2/Shipping/protos/shipping"
	reflect "reflect"
)

// MockIService is a mock of IService interface
type MockIService struct {
	ctrl     *gomock.Controller
	recorder *MockIServiceMockRecorder
}

// MockIServiceMockRecorder is the mock recorder for MockIService
type MockIServiceMockRecorder struct {
	mock *MockIService
}

// NewMockIService creates a new mock instance
func NewMockIService(ctrl *gomock.Controller) *MockIService {
	mock := &MockIService{ctrl: ctrl}
	mock.recorder = &MockIServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockIService) EXPECT() *MockIServiceMockRecorder {
	return m.recorder
}

// Create mocks base method
func (m *MockIService) Create(arg0 models.ShippingAddress) (*models.ShippingAddress, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(*models.ShippingAddress)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create
func (mr *MockIServiceMockRecorder) Create(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIService)(nil).Create), arg0)
}

// GetByCustomerId mocks base method
func (m *MockIService) GetByCustomerId(arg0 int) ([]models.ShippingAddress, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByCustomerId", arg0)
	ret0, _ := ret[0].([]models.ShippingAddress)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByCustomerId indicates an expected call of GetByCustomerId
func (mr *MockIServiceMockRecorder) GetByCustomerId(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCustomerId", reflect.TypeOf((*MockIService)(nil).GetByCustomerId), arg0)
}

// SetAddressToOrder mocks base method
func (m *MockIService) SetAddressToOrder(arg0 string, arg1 int) (*shipping.OrderAddressUpdateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetAddressToOrder", arg0, arg1)
	ret0, _ := ret[0].(*shipping.OrderAddressUpdateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetAddressToOrder indicates an expected call of SetAddressToOrder
func (mr *MockIServiceMockRecorder) SetAddressToOrder(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAddressToOrder", reflect.TypeOf((*MockIService)(nil).SetAddressToOrder), arg0, arg1)
}
