apiVersion: v1
kind: Service
metadata:
  name: customer-account-frontstore-service
spec:
  selector:
    app: customer-account-frontstore
  type: NodePort
  ports:
    - protocol: TCP
      port: 8091
      targetPort: 8091
      nodePort: 30214
---
apiVersion: v1
kind: Service
metadata:  
  name: customer-account-frontstore-grpc-service
spec:
  selector:    
    app: customer-account-frontstore-grpc
  type: NodePort
  ports:  
    - protocol: TCP
      port: 8092
      targetPort: 8092
      nodePort: 30215