apiVersion: v1
kind: Service
metadata:  
  name: category-service
spec:
  selector:    
    app: category
  type: NodePort
  ports:  
    - protocol: TCP
      port: 7450
      targetPort: 7450
      nodePort: 30204
---
apiVersion: v1
kind: Service
metadata:  
  name: category-grpc-service
spec:
  selector:    
    app: category-grpc
  type: NodePort
  ports:  
    - protocol: TCP
      port: 7459
      targetPort: 7459
      nodePort: 30205