apiVersion: v1
kind: Service
metadata:
  name: products-admin-service
spec:
  selector:
    app: products-admin
  type: NodePort
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
      nodePort: 30201
---
apiVersion: v1
kind: Service
metadata:  
  name: products-admin-grpc-service
spec:
  selector:    
    app: products-admin-grpc
  type: NodePort
  ports:  
    - protocol: TCP
      port: 8002
      targetPort: 8002
      nodePort: 30202