apiVersion: v1
kind: Service
metadata:  
  name: products-frontstore-service
spec:
  selector:    
    app: products-frontstore
  type: NodePort
  ports:  
    - protocol: TCP
      port: 8003
      targetPort: 8003
      nodePort: 30203