apiVersion: v1
kind: Service
metadata:
  name: shipping-service
spec:
  selector:
    app: shipping
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8003
      nodePort: 30209
---
apiVersion: v1
kind: Service
metadata:  
  name: shipping-gprc-service
spec:
  selector:    
    app: shipping-gprc
  type: NodePort
  ports:  
    - protocol: TCP
      port: 9001
      targetPort: 9001
      nodePort: 30210