// Code generated by mockery v2.10.1. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	errors "github.com/swiggy-2022-bootcamp/cdp-team2/reward/internal/errors"

	models "github.com/swiggy-2022-bootcamp/cdp-team2/reward/internal/dao/models"
)

// DynamoDAO is an autogenerated mock type for the DynamoDAO type
type DynamoDAO struct {
	mock.Mock
}

// AddReward provides a mock function with given fields: reward
func (_m *DynamoDAO) AddReward(reward models.Reward) *errors.ServerError {
	ret := _m.Called(reward)

	var r0 *errors.ServerError
	if rf, ok := ret.Get(0).(func(models.Reward) *errors.ServerError); ok {
		r0 = rf(reward)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*errors.ServerError)
		}
	}

	return r0
}

// GetReward provides a mock function with given fields: customerId
func (_m *DynamoDAO) GetReward(customerId string) (models.Reward, *errors.ServerError) {
	ret := _m.Called(customerId)

	var r0 models.Reward
	if rf, ok := ret.Get(0).(func(string) models.Reward); ok {
		r0 = rf(customerId)
	} else {
		r0 = ret.Get(0).(models.Reward)
	}

	var r1 *errors.ServerError
	if rf, ok := ret.Get(1).(func(string) *errors.ServerError); ok {
		r1 = rf(customerId)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*errors.ServerError)
		}
	}

	return r0, r1
}
