apiVersion: v1
kind: Service
metadata:  
  name: checkout-service
spec:
  selector:    
    app: checkout
  type: NodePort
  ports:  
    - protocol: TCP
      port: 7451
      targetPort: 7451
      nodePort: 30206