apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-frontstore-deployment
  labels:
    app: auth-frontstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-frontstore
  template:
    metadata:
      labels:
        app: auth-frontstore
    spec:
      containers:
      - name: auth-frontstore
        image: swiggyteam2/auth-frontstore:latest
        ports:
        - containerPort: 8088
---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: products-admin-gprc-deployment
#   labels:
#     app: products-admin-grpc
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: products-admin-grpc
#   template:
#     metadata:
#       labels:
#         app: products-admin-grpc
#     spec:
#       containers:
#       - name: products-admin
#         image: swiggyteam2/products-admin:latest
#         ports:
#         - containerPort: 8002
