apiVersion: v1
kind: Service
metadata:
  name: auth-frontstore-service
spec:
  selector:
    app: auth-frontstore
  type: NodePort
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 8088
      nodePort: 30211
---
# apiVersion: v1
# kind: Service
# metadata:  
#   name: products-admin-grpc-service
# spec:
#   selector:    
#     app: products-admin-grpc
#   type: NodePort
#   ports:  
#     - protocol: TCP
#       port: 8002
#       targetPort: 8002
#       nodePort: 30202