apiVersion: v1
kind: Service
metadata:
  name: customer-ms-service
spec:
  selector:
    app: customer-ms
  type: NodePort
  ports:
    - protocol: TCP
      port: 8093
      targetPort: 8093
      nodePort: 30212
---
apiVersion: v1
kind: Service
metadata:  
  name: customer-ms-grpc-service
spec:
  selector:    
    app: customer-ms-grpc
  type: NodePort
  ports:  
    - protocol: TCP
      port: 8094
      targetPort: 8094
      nodePort: 30213